-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DROP TABLE IF EXISTS Users;
-- CREATE TABLE Users (
--     id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
--     name TEXT NOT NULL,
--     email TEXT UNIQUE NOT NULL,
--     password TEXT NOT NULL
-- );
